#!/bin/sh
show_menu(){
normal=`echo "\033[m"`
    menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
YELLOW='\033[1;33m'
printf "${fgred}         © 尺ᗪ乂 尸尺龱丿㠪⼕ㄒ ᐯ工尸㠪尺 ©      \n"
printf "${menu}      ♛ A̲ C̲o̲m̲p̲l̲e̲t̲e̲l̲y̲ A̲u̲t̲o̲m̲a̲t̲e̲d̲ P̲r̲o̲j̲e̲c̲t̲ ♛         \n"
cat /data/data/com.termux/files/home/Viper/pytransform/Trident | lolcat -a -d 5
   ./Header
    
    printf "\n${menu}████████████████████████████████████████████████████████${normal}\n"
    printf "\n${menu}██${number} 1)${menu} ＢＹＰＡＳＳ ＫＯＲＥＡＮ ${normal}\n\n" | lolcat -a -d 3
    printf "${menu}██${number} 2)${menu} ＢＹＰＡＳＳ ＧＬＯＢＡＬ ${normal}\n\n" | lolcat -a -d 3
    printf "${menu}██${number} 3)${menu} ＢＹＰＡＳＳ ＶＥＩＴＮＡＭ ${normal}\n\n" | lolcat -a -d 3
    printf "${menu}██${number} 4)${menu} ＣＬＥＡＮ ＬＯＧ ${normal}\n\n" | lolcat -a -d 3
    printf "${menu}██${number} 5)${menu} ＲＥＳＥＴ ＧＵＥＳＴ ＡＣＣＯＵＮＴ ${normal}\n\n" | lolcat -a -d 3
    printf "${menu}██${number} 6)${menu} ＣＨＡＮＧＥ ＤＮＳ 8.8.8.8 ${normal}\n\n" | lolcat -a -d 3
    printf "${menu}████████████████████████████████████████████████████████${normal}\n"
    printf "\n${fgred}Please enter a menu option and enter or ${fgred}x to exit. ${normal}"
    read opt
}

option_picked(){
    msgcolor=`echo "\033[01;31m"` # bold red
    normal=`echo "\033[00;00m"` # normal white
    message=${@:-"${normal}Error: No message passed"}
    printf "${msgcolor}${message}${normal}\n"
}

clear
echo " "
echo " "
show_menu
while [ $opt != '' ]
    do
    if [ $opt = '' ]; then
      exit;
    else
      case $opt in
        1) clear;
            option_picked "𝑷𝑼𝑩𝑮 𝑲𝒐𝒓𝒆𝒂𝒏 𝑩𝒚𝒑𝒂𝒔𝒔\n";
            printf "Starting Bypass...\n";
            sleep 2
start=`date +%s`
runtime=$((end-start))
normal=`echo "\033[m"`
menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
YELLOW='\033[1;33m'

if [ -d "/data/data/com.termux/files/home/Viper/pytransform/mods/Paks" ] 
then
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini
rm -rf /storage/emulated/0/.backups/com.pubg.krmobile &> /dev/null
rm -rf /storage/emulated/0/tencent/Midas/Log/com.pubg.krmobile &> /dev/null
rm -rf /data/media/0/MidasOversea/GUID/* &> /dev/null

if [ ! -d "/storage/emulated/0/Android/Trident.Korea" ] 
then
mkdir /storage/emulated/0/Android/Trident.Korea
fi
rsync -avh /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ /storage/emulated/0/Android/Trident.Korea/ &> /dev/null
#mv /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/* /storage/emulated/0/Android/Trident.Korea &> /dev/null
sleep 9
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.0.11462.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.5.11560.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11463.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11464.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11466.pak
echo " "
./progress
echo " "
am start -n com.pubg.krmobile/com.epicgames.ue4.SplashActivity
sleep 6
chmod 664 /data/data/com.pubg.krmobile/lib/libtersafe.so
chmod 664 /data/data/com.pubg.krmobile/lib/libUE4.so
chmod 664 /data/data/com.pubg.krmobile/lib/libtprt.so
sleep 60
c=0
PACKAGE='com.pubg.krmobile'
while [ $(pidof $PACKAGE) ]
do
c=$((c+1))
rm -rf /data/data/com.pubg.krmobile/app_appcache &> /dev/null
rm -rf /data/data/com.pubg.krmobile/app_bugly &> /dev/null
rm -rf /data/data/com.pubg.krmobile/cache &> /dev/null
rm -rf /data/data/com.pubg.krmobile/code_cache &> /dev/null
rm -rf /data/data/com.pubg.krmobile/app_crashrecord &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/google_app_measurement_local.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/pri_tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/xg_message.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/google_app_measurement_local.db &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/pri_tencent_analysis.db &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_issues-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_key_values-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_sessions-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_support_key_values-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/bugly_db_-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs_log_store-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/files/iMSDK &> /dev/null
rm -rf /data/data/com.pubg.krmobile/files/AppEventsLogger.persistedevents &> /dev/null
rm -rf /data/data/com.pubg.krmobile/files/tpnlcache.data &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.5.11560_20200108100228_1861002805_cures.ifs.res &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/tencent &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/Tencent &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/ca-bundle.pem &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/cacheFile.txt &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/vmpcloudconfig.json &> /dev/null
rm -rf /data/data/com.pubg.krmobile/cache/* &> /dev/null
rm -rf /sdcard/Tencent/beacon &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/blob/mqq &> /dev/null
rm -rf /sdcard/Tencent/Midas/Log/com.pubg.krmobile &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_live_log/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_audio_data &> /dev/null
rm -rf /sdcard/Tencent/tbs/backup/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.TbsReaderTempcom.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.thumbnails &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.tmp &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.trooptmp &> /dev/null
rm -rf /sdcard/Tencent/msflogs/com/tencent/mobileqq &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/.apollo/game &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/capture_qsvf &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/dov_ptv_template_dov &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/WebViewCheck &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/log &> /dev/null
rm -rf /data/data/com.pubg.krmobile/code_cache/* &> /dev/null
printf "\n${fgred}██████████████████████████${normal}\n"
printf "${menu}██████████"
printf "${menu}Loop ${fgred}=> ${normal}$c"
sleep 10
if [ ! $(pidof $PACKAGE) ]; then
break
fi
sleep 1
done
chmod 755 /data/data/com.pubg.krmobile/lib/libtersafe.so
chmod 755 /data/data/com.pubg.krmobile/lib/libUE4.so
chmod 755 /data/data/com.pubg.krmobile/lib/libtprt.so
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/* &> /dev/null
echo " "
rsync -avh /storage/emulated/0/Android/Trident.Korea/ /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ &> /dev/null
sleep 9
rm -rf /storage/emulated/0/Android/Trident.Korea &> /dev/null
end=`date +%s`
runtime=$((end-start))
runmin=$((runtime/60))
echo " "
printf "\n${fgred}███████████${menu}Total Execution Time : ${fgred}$runmin Minuts ${fgred}█████████████${normal}\n"
echo " "
./progress
echo " "
printf "${YELLOW}  Client Restored"
echo " "
else
 echo "${YELLOW} Korea Support Is Not Available"
fi
            sleep 2
            echo " "
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
        2) clear;
            option_picked "𝑷𝑼𝑩𝑮 𝑮𝒍𝒐𝒃𝒂𝒍 𝑩𝒚𝒑𝒂𝒔𝒔\n";
            printf "Bypassing Global...\n";
start=`date +%s`
runtime=$((end-start))
normal=`echo "\033[m"`
menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
YELLOW='\033[1;33m'

if [ -d "/data/data/com.termux/files/home/Viper/pytransform/mods/Paks" ] 
then
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini
rm -rf /storage/emulated/0/.backups/com.tencent.ig &> /dev/null
rm -rf /data/media/0/MidasOversea/GUID/* &> /dev/null

if [ ! -d "/storage/emulated/0/Android/Trident.Global" ] 
then
mkdir /storage/emulated/0/Android/Trident.Global
fi

rsync -avh /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ /storage/emulated/0/Android/Trident.Global/ &> /dev/null
sleep 9
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.0.11462.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.5.11560.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11463.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11464.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11466.pak
echo " "
./progress
echo " "
am start -n com.tencent.ig/com.epicgames.ue4.SplashActivity
sleep 6
chmod 664 /data/data/com.tencent.ig/lib/libtersafe.so
chmod 664 /data/data/com.tencent.ig/lib/libUE4.so
chmod 664 /data/data/com.tencent.ig/lib/libtprt.so
sleep 60
c=0
PACKAGE='com.tencent.ig'
while [ $(pidof $PACKAGE) ]
do
c=$((c+1))
rm -rf /data/data/com.tencent.ig/app_appcache &> /dev/null
rm -rf /data/data/com.tencent.ig/app_bugly &> /dev/null
rm -rf /data/data/com.tencent.ig/cache &> /dev/null
rm -rf /data/data/com.tencent.ig/code_cache &> /dev/null
rm -rf /data/data/com.tencent.ig/app_crashrecord &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/google_app_measurement_local.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/pri_tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/xg_message.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/google_app_measurement_local.db &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/pri_tencent_analysis.db &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_issues-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_key_values-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_sessions-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_support_key_values-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/bugly_db_-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs_log_store-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/files/iMSDK &> /dev/null
rm -rf /data/data/com.tencent.ig/files/AppEventsLogger.persistedevents &> /dev/null
rm -rf /data/data/com.tencent.ig/files/tpnlcache.data &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.5.11560_20200108100228_1861002805_cures.ifs.res &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/tencent &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/Tencent &> /dev/null
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/ca-bundle.pem &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/cacheFile.txt &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/vmpcloudconfig.json &> /dev/null
rm -rf /data/data/com.tencent.ig/cache/* &> /dev/null
rm -rf /sdcard/Tencent/beacon &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/blob/mqq &> /dev/null
rm -rf /sdcard/Tencent/Midas/Log/com.tencent.ig &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_live_log/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_audio_data &> /dev/null
rm -rf /sdcard/Tencent/tbs/backup/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.TbsReaderTempcom.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.thumbnails &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.tmp &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.trooptmp &> /dev/null
rm -rf /sdcard/Tencent/msflogs/com/tencent/mobileqq &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/.apollo/game &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/capture_qsvf &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/dov_ptv_template_dov &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/WebViewCheck &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/log &> /dev/null
rm -rf /data/data/com.tencent.ig/code_cache/* &> /dev/null
printf "\n${fgred}██████████████████████████${normal}\n"
printf "${menu}██████████"
printf "${menu}Loop ${fgred}=> ${normal}$c"

sleep 10
if [ ! $(pidof $PACKAGE) ]; then
break
fi
sleep 1
done
chmod 755 /data/data/com.tencent.ig/lib/libtersafe.so
chmod 755 /data/data/com.tencent.ig/lib/libUE4.so
chmod 755 /data/data/com.tencent.ig/lib/libtprt.so
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/* &> /dev/null
echo " "
rsync -avh /storage/emulated/0/Android/Trident.Global/ /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ &> /dev/null
sleep 9
rm -rf /storage/emulated/0/Android/Trident.Global/*
end=`date +%s`
runtime=$((end-start))
runmin=$((runtime/60))
echo " "
printf "\n${fgred}███████████${menu}Total Execution Time : ${fgred}$runmin Minuts ${fgred}█████████████${normal}\n"
echo " "
./progress
echo " "
printf "${YELLOW}  Client Restored"
echo " "
else
 echo "${YELLOW} Global Support Is Not Available"
fi
            sleep 2
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
         3) clear;
            option_picked "ＰＵＢＧ ＶＮ ＢＹＰＡＳＳ\n";
            printf "Starting Bypass...\n";
            sleep 2
start=`date +%s`
runtime=$((end-start))
normal=`echo "\033[m"`
menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
YELLOW='\033[1;33m'

if [ -d "/data/data/com.termux/files/home/Viper/pytransform/mods/Paks" ] 
then
rm -rf /sdcard/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini
rm -rf /storage/emulated/0/.backups/com.vng.pubgmobile &> /dev/null
rm -rf /storage/emulated/0/tencent/Midas/Log/com.vng.pubgmobile &> /dev/null
rm -rf /data/media/0/MidasOversea/GUID/* &> /dev/null

if [ ! -d "/storage/emulated/0/Android/Trident.Korea" ] 
then
mkdir /storage/emulated/0/Android/Trident.Korea
fi
rsync -avh /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ /storage/emulated/0/Android/Trident.Korea/ &> /dev/null
#mv /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/* /storage/emulated/0/Android/Trident.Korea &> /dev/null
sleep 9
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.0.11462.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_0.16.5.11560.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11463.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11464.pak
base64 --decode /data/data/com.termux/files/home/Viper/🔱 > /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_0.16.0.11466.pak
echo " "
./progress
echo " "
echo "CONNECTING TO SERVER"
iptables -I INPUT -s app.adjust.com -j DROP &>/dev/null
iptables -I INPUT -s app-measurement.com -j DROP &>/dev/null
iptables -I INPUT -s rtb.astrodsp.com -j DROP &>/dev/null
iptables -I INPUT -s d3py17yaayq4xi.cloudfront.net -j DROP &>/dev/null
iptables -I INPUT -s sin.creativecdn.com -j DROP &>/dev/null
iptables -I INPUT -s statics-asia.creativecdn.com -j DROP &>/dev/null
iptables -I INPUT -s data.flurry.com -j DROP &>/dev/null
iptables -I INPUT -s .gameguardian.net -j DROP &>/dev/null
iptables -I INPUT -s raw.githubusercontent.com -j DROP &>/dev/null
iptables -I INPUT -s .helpshift.com -j DROP &>/dev/null
iptables -I INPUT -s meping.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s file.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s euping.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s ig-us-notice.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s lobby.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s pay.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s saping.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s krping.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s public.igamecj.com -j DROP &>/dev/null
iptables -I INPUT -s cloud.gsdk.proximabeta.com -j DROP &>/dev/null
iptables -I INPUT -s www.pubgmobile.com -j DROP &>/dev/null
iptables -I INPUT -s q.qlogo.cn -j DROP &>/dev/null
iptables -I INPUT -s cs.mbgame.gamesafe.qq.com -j DROP &>/dev/null
iptables -I INPUT -s c.tdm.qq.com -j DROP &>/dev/null
iptables -I INPUT -s vmp.qq.com -j DROP &>/dev/null
iptables -I INPUT -s intldlgs.qq.com -j DROP &>/dev/null
iptables -I INPUT -s intl.cloud.tencent.com -j DROP &>/dev/null
iptables -I INPUT -s intl.mtp.tencent.com -j DROP &>/dev/null
iptables -I INPUT -s mtp@tencent.com -j DROP &>/dev/null
iptables -I INPUT -s csoversea.mbgame.gamesafe.qq.com -j DROP &>/dev/null
iptables -I INPUT -s .qq.com -j DROP &>/dev/null
iptables -I INPUT -s google.com -j DROP &>/dev/null
iptables -I INPUT -s qq.com -j DROP &>/dev/null
iptables -I INPUT -s napubgm.broker.tplay.qq.com -j DROP &>/dev/null
iptables -I INPUT -s googleusercontent.com -j DROP &>/dev/null
iptables -I INPUT -s .googleusercontent.com -j DROP &>/dev/null
iptables -I INPUT -s 182.254.116.117/80 -j DROP &>/dev/null
sleep 1
echo ""
echo "STARTING GAME PUBG VN 16.5 BYPASS"
am start -n com.vng.pubgmobile/com.epicgames.ue4.SplashActivity
sleep 5
echo ""
echo "INJECTING PERMISSIONS FROM SERVER"
chmod -R 755 /data/data/com.vng.pubgmobile/lib/libabase.so &> /dev/null
chmod -R 755 /data/data/com.vng.pubgmobile/lib/liblbs.so &> /dev/null
chmod -R 755 /data/data/com.vng.pubgmobile/lib/libtersafe.so &> /dev/null
chmod -R 755 /data/data/com.vng.pubgmobile/lib/libtprt.so &> /dev/null
chmod -R 755 /data/data/com.vng.pubgmobile/lib/libUE4.so &> /dev/null
chmod -R 755 /data/data/com.vng.pubgmobile/lib/libzip.so &> /dev/null
chmod -R 755 /data/data/com.vng.pubgmobile/lib/libzlib.so &> /dev/null
echo "GETTING PACKAGES FROM SERVER"
sleep 40
echo "
▄▀█ █░░ █░░   █░░ █▀█ █▀▀   █▀▀ █░░ █▀▀ ▄▀█ █▀█
█▀█ █▄▄ █▄▄   █▄▄ █▄█ █▄█   █▄▄ █▄▄ ██▄ █▀█ █▀▄"
echo "
█▀ ▀█▀ ▄▀█ █▀█ ▀█▀ █ █▄░█ █▀▀
▄█ ░█░ █▀█ █▀▄ ░█░ █ █░▀█ █▄█" 
COUNT=1
[ $COUNT ];
cleaner()
{
rm -rf /data/user/0/com.vng.pubgmobile/shared_prefs &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/no_backup &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/files &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/databases &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/cache &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_crashrecord &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_bugly &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_geolocation &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_webview_imsdk_inner_webview &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_webview &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_textures &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_tbs &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_databases &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/app_appcache &> /dev/null
rm -rf /data/user/0/com.vng.pubgmobile/code_cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ODPaks/ &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1950038955_3090_0.16.5.11560_20200108020124_1155095217_cures.ifs.res &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/UserCustom.ini &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /storage/emulated/0/.backups &> /dev/null
rm -rf /storage/emulated/0/tencent &> /dev/null
#echo "Cleaning = $COUNT at $( date +"%H:%M:%S" )"
let COUNT=COUNT+1
} 
PACKAGE='com.vng.pubgmobile'
while [ $(pidof $PACKAGE) ]
do
cleaner
if [ ! $(pidof $PACKAGE) ]; then
break
fi
done
sleep 2
echo "" 
echo "" 
echo "Game stopped, Resetting all Files" 
echo ""
sleep 1
((final=$COUNT+1))
printf " █ NUMBER OF TIME CLEARED █---------> ";
echo $final
echo "" 
sleep 1
((report=$COUNT/500))
printf "Number of report Stopped = ";
echo $report
echo "" 
printf ">>>From All Reports we Finally stop ";
echo $report "Report" 
echo "To get access to the Server Database " 
su -c iptables --flush
echo "" 
chmod 755 /data/data/com.vng.pubgmobile/lib/libtersafe.so
chmod 755 /data/data/com.vng.pubgmobile/lib/libUE4.so
chmod 755 /data/data/com.vng.pubgmobile/lib/libtprt.so
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/* &> /dev/null
echo " "
rsync -avh /storage/emulated/0/Android/Trident.Korea/ /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ &> /dev/null
sleep 9
rm -rf /storage/emulated/0/Android/Trident.Korea &> /dev/null
end=`date +%s`
runtime=$((end-start))
runmin=$((runtime/60))
echo " "
printf "\n${fgred}███████████${menu}Total Execution Time : ${fgred}$runmin Minuts ${fgred}█████████████${normal}\n"
echo " "
./progress
echo " "
printf "${YELLOW}  Client Restored"
echo " "
else
 echo "${YELLOW} Korea Support Is Not Available"
fi
            sleep 2
            echo " "
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
        4) clear;
            option_picked "Log Cleaner\n";
            printf "Cleaning Logs...\n";
            echo " "
            ./progress
            rm -rf /data/data/com.pubg.krmobile/app_appcache &> /dev/null
rm -rf /data/data/com.pubg.krmobile/app_bugly &> /dev/null
rm -rf /data/data/com.pubg.krmobile/cache &> /dev/null
rm -rf /data/data/com.pubg.krmobile/code_cache &> /dev/null
rm -rf /data/data/com.pubg.krmobile/app_crashrecord &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/google_app_measurement_local.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/pri_tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/xg_message.db-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/google_app_measurement_local.db &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/pri_tencent_analysis.db &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_issues-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_key_values-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_sessions-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs__db_support_key_values-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/bugly_db_-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/databases/__hs_log_store-journal &> /dev/null
rm -rf /data/data/com.pubg.krmobile/files/iMSDK &> /dev/null
rm -rf /data/data/com.pubg.krmobile/files/AppEventsLogger.persistedevents &> /dev/null
rm -rf /data/data/com.pubg.krmobile/files/tpnlcache.data &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
cp /data/data/com.termux/files/home/Viper/pytransform/AntiCheat.ini /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.5.11560_20200108100228_1861002805_cures.ifs.res &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/tencent &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/Tencent &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/ca-bundle.pem &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/cacheFile.txt &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/vmpcloudconfig.json &> /dev/null
rm -rf /data/data/com.pubg.krmobile/cache/* &> /dev/null
rm -rf /sdcard/Tencent/beacon &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/blob/mqq &> /dev/null
rm -rf /sdcard/Tencent/Midas/Log/com.pubg.krmobile &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_live_log/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_audio_data &> /dev/null
rm -rf /sdcard/Tencent/tbs/backup/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.TbsReaderTempcom.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.thumbnails &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.tmp &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.trooptmp &> /dev/null
rm -rf /sdcard/Tencent/msflogs/com/tencent/mobileqq &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/.apollo/game &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/capture_qsvf &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/dov_ptv_template_dov &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/WebViewCheck &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/log &> /dev/null
rm -rf /data/data/com.pubg.krmobile/code_cache/* &> /dev/null
rm -rf /data/data/com.tencent.ig/app_appcache &> /dev/null
rm -rf /data/data/com.tencent.ig/app_bugly &> /dev/null
rm -rf /data/data/com.tencent.ig/cache &> /dev/null
rm -rf /data/data/com.tencent.ig/code_cache &> /dev/null
rm -rf /data/data/com.tencent.ig/app_crashrecord &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/google_app_measurement_local.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/pri_tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/tencent_analysis.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/xg_message.db-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/google_app_measurement_local.db &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/pri_tencent_analysis.db &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_issues-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_key_values-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_sessions-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs__db_support_key_values-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/bugly_db_-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/databases/__hs_log_store-journal &> /dev/null
rm -rf /data/data/com.tencent.ig/files/iMSDK &> /dev/null
rm -rf /data/data/com.tencent.ig/files/AppEventsLogger.persistedevents &> /dev/null
rm -rf /data/data/com.tencent.ig/files/tpnlcache.data &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
cp /data/data/com.termux/files/home/Viper/pytransform/AntiCheat.ini /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_uuid_define.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/apollo_loglist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_47_0.16.5.11560_20200108100228_1861002805_cures.ifs.res &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_res.eifs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/tencent &> /dev/null
rm -rf /sdcard/.backups &> /dev/null
rm -rf /sdcard/Tencent &> /dev/null
rm -rf /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/cache &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/tbslog &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/ca-bundle.pem &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/cacheFile.txt &> /dev/null
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/vmpcloudconfig.json &> /dev/null
rm -rf /data/data/com.tencent.ig/cache/* &> /dev/null
rm -rf /sdcard/Tencent/beacon &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/blob/mqq &> /dev/null
rm -rf /sdcard/Tencent/Midas/Log/com.tencent.ig &> /dev/null
rm -rf /sdcard/Tencent/wtlogin/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_live_log/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs_audio_data &> /dev/null
rm -rf /sdcard/Tencent/tbs/backup/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/tbs/com.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.TbsReaderTempcom.tencent.mobileqq &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.thumbnails &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.tmp &> /dev/null
rm -rf /sdcard/Tencent/QQfile_recv/.trooptmp &> /dev/null
rm -rf /sdcard/Tencent/msflogs/com/tencent/mobileqq &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/.apollo/game &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/capture_qsvf &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/dov_ptv_template_dov &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/WebViewCheck &> /dev/null
rm -rf /sdcard/Tencent/MobileQQ/log &> /dev/null
rm -rf /data/data/com.tencent.ig/code_cache/* &> /dev/null
            sleep 2
            echo " "
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
        5) clear;
            option_picked "Guest Reset\n";
            printf "Resetting Your Guest Account...\n";
            echo " "
            KR="/data/data/com.pubg.krmobile/shared_prefs/device_id.xml"
            kill com.pubg.krmobile 2> /dev/null
            rm -rf $KR
            echo "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name=\"random\"></string>
    <string name=\"install\"></string>
    <string name=\"uuid\">$RANDOM$RANDOM-$RANDOM-$RANDOM-$RANDOM-$RANDOM$RANDOM$RANDOM</string>
</map>" > $KR
./progress
sleep 2
            echo " "
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
         6) clear;
            option_picked "Dns Changer\n";
            printf "Changing Dns...\n";
            ./pytransform/__pycache__/google
            echo " "
            printf "Dns Changed To Google 8.8.8.8 On Port 53\n";
           sleep 2
            echo "Exiting To Driver Code"
            sleep 2
            clear
             show_menu;
        ;;
        x)
        
printf "${YELLOW}Project & Created by :-\n"
printf "\n${YELLOW}-------------------------------------------------"
printf "\n${YELLOW}██╗   ██╗██╗██████╗ ███████╗██████╗ "
printf "\n${YELLOW}██║   ██║██║██╔══██╗██╔════╝██╔══██╗"
printf "\n${YELLOW}██║   ██║██║██████╔╝█████╗  ██████╔╝"
printf "\n${YELLOW}╚██╗ ██╔╝██║██╔═══╝ ██╔══╝  ██╔══██╗"
printf "\n${YELLOW} ╚████╔╝ ██║██║     ███████╗██║  ██║"
printf "\n${YELLOW}  ╚═══╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝"
printf "\n${YELLOW}"
printf "\n${YELLOW} █▀█ █▀▄ ▀▄▀   █░█ █ ▄▀█   █▀ █░█ ▄▀█ ▄▀█ █▄░█"
printf "\n${YELLOW} █▀▄ █▄▀ █░█   ▀▄▀ █ █▀█   ▄█ █▀█ █▀█ █▀█ █░▀█"
printf "\n${YELLOW}--------------------------------------------------"
        exit;
        ;;
        \n)exit;
        ;;
        *)clear;
            option_picked "Pick an option from the menu";
            show_menu;
        ;;
      esac
    fi
done
